/* filename main.cpp
 * Main file that calls the QApplication in mainwindow.cpp
 * Last updated: [DD:MM:YYYY]
 * Description of latest update:
 *
 * File generated by Qt
 */

#include "mainwindow.h"
#include "Points.h"
#include "Chess/board.h"


#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();


    return a.exec();
}
